name: 'macro_data_platform1'
version: '1.0.0'
config-version: 2

profile: 'macro_data_platform1'

model-paths: ["models"]
test-paths: ["tests"]

models:
  macro_data_platform1:
    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: analytics
      +materialized: table